/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Lasr_langStandaloneSetup extends Lasr_langStandaloneSetupGenerated {

	def static void doSetup() {
		new Lasr_langStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
